### ISSUE TITLE
Jamming - Summary 

### ISSUE THREAD

**Issue by ad3429** [renuez/codecademy-frontend-webapp-jamming#16]
**Summary Grade: Satisfactory**

Great job! I have left some comments in your code that you can check out by navigating to the "Issues" on the top bar here. You generally did an excellent job with all of your files -- they are nicely written and you generally followed good coding practices. Just some small things I noticed: in your addTrack function in your App.js file you should first check to see if the track is added and if it is, then you can just return. This would look something like:

<img width="578" alt="42014842-77cd67fe-7a72-11e8-8679-249ebce03c91" src="https://user-images.githubusercontent.com/25671399/48811767-32ebdf00-ecfd-11e8-9eff-7135cc9bb8dc.png">

Moreover, it may be a good idea to install a JS extension that automatically formats your code for you. Here's one good example of such an extension:

https://prettier.io/

Overall you did an excellent job with this project, and it's clear that you have grown as a React developer. Make sure to keep up the good work!

**Comment by renuez** [comment]
@ad3429 👍
Many thanks for your review and your very helpful recommendation as well!
